CC = gcc
CFLAGS = -std=c99 -Wall -Wextra -pedantic -g
LDFLAGS = -lcunit -lm
SRC = unit_tests.c yee_common.c
OBJ = $(SRC:.c=.o)
BIN = unit_tests

.PHONY: test clean

all: $(BIN)

test: $(BIN)
	./$(BIN)

$(BIN): $(OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

clean: 
	$(RM) $(BIN) $(OBJ)
