CC = gcc
CFLAGS = -std=c99 -Wall -Wextra -pedantic
LDFLAGS = -lcunit -lm
SRC = CU_main.c yee_common.c
OBJ = $(SRC:.c=.o)
BIN = CU_main

.PHONY: test clean

all: $(BIN)

test: $(BIN)
	./$(BIN)

$(BIN): $(OBJ)
	$(CC) $^ $(LDFLAGS) -o $@

clean: 
	$(RM) $(BIN) $(OBJ)
